name: fomu_ci
on: [push, pull_request]
jobs:
  check-multi-proj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: bash scripts/setup -ci
      - run: which pip3 && which python3 && which pip
      - run: make env
      - run: which pip3 && which python3 && which pip
      - run: riscv64-elf-gcc --version
      - run: pwd && source env/conda/bin/activate cfu-common && source environment && yosys --version && nextpnr-ice40 --version
      - run: pwd && source env/conda/bin/activate cfu-common && source environment && cd proj/proj_template_v && pip3 list && make TARGET=kosagi_fomu bitstream
      - run: pwd && source env/conda/bin/activate cfu-common && source environment && cd proj/kws_micro_accel && pip3 list && make TARGET=kosagi_fomu bitstream || true
